// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20220118234156_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Travel.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 2,
                            City = "New York",
                            Country = "United States",
                            Rating = 3,
                            Review = "Awesome city to visit!",
                            State = "New York"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Seattle",
                            Country = "United States",
                            Rating = 7,
                            Review = "Awesome city to visit!",
                            State = "Washington"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Houston",
                            Country = "United States",
                            Rating = 7,
                            Review = "Awesome city to visit!",
                            State = "Texas"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Portland",
                            Country = "United States",
                            Rating = 8,
                            Review = "Awesome city to visit!",
                            State = "Oregon"
                        },
                        new
                        {
                            DestinationId = 6,
                            City = "Boise",
                            Country = "United States",
                            Rating = 5,
                            Review = "Awesome city to visit!",
                            State = "Idaho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
